### ISSUE TITLE
Δε γίνεται αναβάθμιση του shelldio από τη γραμμή εντολών

### ISSUE THREAD

**Issue by billniakas** [CerebruxCode/shelldio#103]
Ύστερα από διαγραφή του φακέλου `.shelldio` και καθαρή εγκατάσταση στην αναβάθμιση του πακέτου παίρνω το ακόλουθο μήνυμα
```
shelldio -u
Θέλεις να γίνει αναβάθμιση του shelldio; (y/n)y
Γίνεται αναβάθμιση του shelldio
fatal: not a git repository (or any of the parent directories): .git
Κάποιο πρόβλημα παρουσιάστηκε κατά την αναβάθμιση. Δοκίμασε ξανά αργότερα
Θέλεις να γίνει αναβάθμιση του shelldio; (y/n)
```

![Screenshot from 2020-11-06 18-21-46](https://user-images.githubusercontent.com/12209936/98389669-0867cd80-205d-11eb-9eca-b3697d1233c2.png)

**Comment by zoispag** [comment]
Good catch @billniakas. Σε όλες τις δοκιμές μοτ, τύχαινε να είμαι ήδη στο directory. 
![image](https://user-images.githubusercontent.com/21138205/98389934-026dee80-2055-11eb-9633-19b3daa86eb2.png)

@cerebrux δικό μου αυτό! :)

**Comment by cerebrux** [comment]
Η εγκατάσταση έγινε σε ARCH Linux από το AUR. Σε αυτή την περίπτωση το `shelldio -u` δεν θα δουλέψει αφού έχει γίνει εγκατάσταση με package manager. 
Παρότι στο `shelldio -h` help μπορεί να αναφέρεται ότι η αναβάθμιση ισχύει μονο σε αυτούς που έχουν κατεβάσει μέσω git clone, παρόλα αυτά μπορεί να μην το προσέξει όπως ο @billniakas.

Αν και δεν έχουν γίνει αρκετά report για αυτό το θέμα ίσως να μπορεί να δημιουργηθεί μια συνθήκη : 

- Ο χρήστης τρέχει `shelldio -u`
- το shelldio ελέγχει αν είναι εγκατεστημένο με git clone, ή οτι υπάρχει το `.git` folder
- Αν δεν ισχύσει το παραπάνω θα πρέπει να του εμφανίσει π.χ. "Η αναβάθμιση μέσω -u υποστηρίζεται μόνο όταν το shelldio έχει γίνει εγκατάσταση με `git clone`"
- Αλλιώς προχωράει κανονικά
