### ISSUE TITLE
Προσθήκη λειτουργίας new_station

### ISSUE THREAD

**Issue by tasakos-dev** [CerebruxCode/shelldio#106]
Προσθήκη λειτουργίας new_station η οποία προσθέτει έναν νέο σταθμό στο all_station.txt

**Comment by cerebrux** [comment]
Από ότι βλέπω ο νέος σταθμός με την επιλογή `-n` προτίθεται στο `all_stations`. Αυτό είναι ασύμβατο με την επιλογή `-f` που έχει το shelldio.
```
-f, --fresh: 	Κατεβάζει εκ νέου την γενική λίστα των ραδιοφωνικών σταθμών με επικαιροποιημένους
	        ραδιοφωνικούς σταθμούς, διορθωμένα links αλλά και νέους ραδιοφωνικούς σταθμούς
```
Π.χ. ο χρήστης προσθέτει έναν νέο σταθμό με την επιλογή `-n`. Κάποια άλλη στιγμή, πάει και προσθέτει άλλα 10...
Μετά από κάνα μήνα, μαθαίνει ότι έχουμε προσθέσει νέους σταθμούς στην εφαρμογή, και λέει "Α ωραία, κάτσε να πάρω τους σταθμούς" και τρέχει `shelldio -f`... αυτό όπως καταλαβαίνεις πάει και αντικαθιστά το αρχείο  `all_stations` με το νέο, οπότε χάνονται όλες οι προσθήκες που έκανε.

Θα μπορούσε εναλλακτικά η επιλογή `-n` να δουλεύει στο `my_stations` το οποίο είναι του χρήστη και το `shelldio` δεν το πειράζει.

Τι λες ?

**Comment by zoispag** [comment]
> Μετά από κάνα μήνα, μαθαίνει ότι έχουμε προσθέσει νέους σταθμούς στην εφαρμογή, και λέει "Α ωραία, κάτσε να πάρω τους σταθμούς" και τρέχει `shelldio -f`... αυτό όπως καταλαβαίνεις πάει και αντικαθιστά το αρχείο  `all_stations` με το νέο, οπότε χάνονται όλες οι προσθήκες που έκανε.

Για την ακρίβεια, το update μέσω git δε θα δουλεύει πια γιατί το αρχείο θα έχει conflicts.

**Comment by tasakos-dev** [comment]
Άρα να κάνω την αλλαγή ώστε να πειράζει το αρχείο `my_stations `και να κάνω νέο pull request?

**Comment by zoispag** [comment]
> Άρα να κάνω την αλλαγή ώστε να πειράζει το αρχείο `my_stations `και να κάνω νέο pull request?

Μπορείς να το κανείς και στο ίδιο PR. Δεν χρειάζεται καινούριο! 🙂

**Comment by cerebrux** [comment]
Ενσωματώθηκε επιτυχώς ! Μπράβο !
