### ISSUE TITLE
Προσθήκη Web Radio Point - Pop και Λαϊκο

### ISSUE THREAD

**Issue by sargirio** [CerebruxCode/shelldio#11]
**Point-Radio**
Point Pop: http://78.46.149.5:8029/stream2
Point Λαικό: http://78.46.149.5:8029/stream

**Comment by cerebrux** [comment]
Ευχαριστούμε !! Μόλις το προσθέσουμε θα ενημερωθείς

**Comment by cerebrux** [comment]
fixed in https://github.com/CerebruxCode/shelldio/commit/42b465a80515aa14f660047cc1a96d01bda33439
