### ISSUE TITLE
Προσθήκη σταθμών

### ISSUE THREAD

**Issue by RaptaG** [CerebruxCode/shelldio#119]
Γεια σας και μπράβο για την δουλειά σας με το shelldio! Μήπως θα μπορούσατε να προσθέσετε τους παρακάτω σταθμούς:

https://www.greekradios.gr/live/862/Free
http://www.youfmradio.gr/

Ευχαριστώ πολύ!

**Comment by cerebrux** [comment]
Φυσικά ! Μόλις τα προσθέσουμε θα ενημερωθείς !
Ευχαριστούμε !

**Comment by Rapta-08** [comment]
Εντάξει. Ευχαριστώ και πάλι!

**Comment by navasr21** [comment]
Πολύ καλή δουλειά. Μπράβο!
Αν θέλετε προσθέστε και αυτούς τους σταθμούς

https://avlikos.gr/

http://www.musicsociety.gr/

https://www.1431am.org/

http://radioparasita.org/

http://www.radio-revolt.net/

https://radiofragmata.org/

https://radioantiregime.espivblogs.net/

Ευχαριστώ πολύ!

**Comment by Tario78** [comment]
Ωραίο και πολύ πρακτικό το shelldio. Συγχαρητήρια!
Μήπως μπορείτε να προσθέσετε και αυτά τα ραδιόφωνα;

https://www.thepressproject.gr
http://bluesradio.gr

Ευχαριστώ

**Comment by cerebrux** [comment]
Μπήκαν όσα είχαν απευθείας λινκ στο url. τα υπόλοιπα δεν τα βρήκαμε εύκολα
