### ISSUE TITLE
Διόρθωση url σταθμού

### ISSUE THREAD

**Issue by citakis** [CerebruxCode/shelldio#122]
Στο αρχείο all_stations.txt line 96 το url του σταθμού ανήκει στον Kriti fm αντί για τον WaveFM.
To url που δουλεύει είναι το https://mediacp.32bit.gr:8018/stream

**Comment by cerebrux** [comment]
Ευχαριστούμε για την αναφορά σφάλματος. διορθώθηκε θα είναι διαθέσιμο στην επόμενη αναβάθμιση
