### ISSUE TITLE
προσθήκη ραδιοσταθμών που δεν υπάρχουν 

### ISSUE THREAD

**Issue by Tropeas** [CerebruxCode/shelldio#124]
Όνομα Σταθμού συχνότητα fm & τοποθεσία > site > stream link 

Κοινωνικό Ραδιόφωνο Χανίων > https://kpaxradio.live > http://78.47.193.254:8006/stream 

Ραδιοφωνικός Σταθμός Πανεπιστημίου Κρήτης (Ηράκλειο) 96,7 FM > https://rastapank.radio.uoc.gr > https://rs.radio.uoc.gr:8001/uoc_128.ogg

Ματζόρε ο σταθμός του Πανεπιστημίου Κρήτης (Ρέθυμνο)  89,1 FM > http://matzore.radio.uoc.gr > http://radio.uoc.gr:8000/matzore_128.ogg

RAT FM Ραδιοφωνικός σταθμός του Ελληνικού Μεσογειακού Πανεπιστημίου Κρήτης (Χανιά) > www.ratfm.gr > http://78.129.222.70:38169

Μετα δεύτερο (Αθήνα) > www.metadeftero.gr > http://live.metadeftero.gr/stream

The press project radio (Αθήνα) > http://thepressproject.gr/radio > http://n0d.radiojar.com/qgra821mrtwtv?rj-ttl=5&rj-tok=AAABegrjf6UAxLBpSgc_nlFBKg

**Comment by cerebrux** [comment]
Το Maztore, RAT FM μόνο δεν μπήκε διότι δεν πάιζει το λινκ

**Comment by Tropeas** [comment]
Διορθώσεις:

Κοινωνικό Ραδιόφωνο Χανίων > [https://kpaxradio.live/](https://kpaxradio.live/) > [https://c32.radioboss.fm:18563/stream](https://c32.radioboss.fm:18563/stream) **<- νεο stream link**

Ματζόρε ο σταθμός του Πανεπιστημίου Κρήτης (Ρέθυμνο) 89,1 FM > [https://matzore.radio.uoc.gr/](https://matzore.radio.uoc.gr/) > [https://rs.radio.uoc.gr:8001/matzore_64.ogg](https://rs.radio.uoc.gr:8001/matzore_64.ogg) **<-νέο stream link (σχετικά με το site έχει τύχει και εγω να το δω κάτω με error 404 παροδικά αλλά επανέρχεται)**

RAT FM Ραδιοφωνικός σταθμός του Ελληνικού Μεσογειακού Πανεπιστημίου Κρήτης (Χανιά) > [[www.ratfm.gr](http://rat-fm.weebly.com/)](http://rat-fm.weebly.com/) > [http://78.129.185.84:31467/](http://78.129.185.84:31467/) **<- νεο site & stream link**

**Comment by cerebrux** [comment]
> Διορθώσεις:
> 
> Κοινωνικό Ραδιόφωνο Χανίων > https://kpaxradio.live/ > https://c32.radioboss.fm:18563/stream **<- νεο stream link**
> 
> Ματζόρε ο σταθμός του Πανεπιστημίου Κρήτης (Ρέθυμνο) 89,1 FM > https://matzore.radio.uoc.gr/ > https://rs.radio.uoc.gr:8001/matzore_64.ogg **<-νέο stream link (σχετικά με το site έχει τύχει και εγω να το δω κάτω με error 404 παροδικά αλλά επανέρχεται)**
> 
> RAT FM Ραδιοφωνικός σταθμός του Ελληνικού Μεσογειακού Πανεπιστημίου Κρήτης (Χανιά) > http://rat-fm.weebly.com/ > http://78.129.185.84:31467/ **<- νεο site & stream link**

Ok Προτέθηκαν

**Comment by kpaxradio** [comment]
Έχουμε την αίσθηση ότι το μεταδεύτερο λόγω άλλης χρήσης του χώρου που είχε σαν στούντιο στο πατάρι του Merlin's music box, και σε επικοινωνία με κάποιους παραγωγούς που γνωρίζαμε επιβαεβαιώνουμε ότι έχει σταματήσει το stream του, άρα χρειάζεται αφαίρεση δυστυχώς πλέον απο την λίστα.
