### ISSUE TITLE
Δεν δουλεύει σε mac

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#13]
```
Διαλέξτε Σταθμό (Q/q για έξοδο): 1
+ [[ 1 = \q ]]
+ [[ 1 = \Q ]]
+ '[' 1 -gt 0 ']'
+ '[' 1 -le 3 ']'
./shelldio.sh: line 64: "1" : syntax error: operand expected (error token is ""1" ")
++ tail -n1
++ cut -d , -f1
+ stathmos_name=
./shelldio.sh: line 65: "1" : syntax error: operand expected (error token is ""1" ")
```

Επίσης αν η επιλογή σταθμού αποτύχει, πρέπει να κρασάρει και όχι να "νομίζει" ότι παίζει τον σταθμό.

**Comment by JohnGavr** [comment]
@drpaneas την λίστα των σταθμών στην εμφάνισε κανονικά;

**Comment by drpaneas** [comment]
> @drpaneas την λίστα των σταθμών στην εμφάνισε κανονικά;

Ναι

**Comment by JohnGavr** [comment]
Έχω δημιουργήσει ένα branch features και ο τρόπος που γίνεται η αναπαραγωγή είναι λίγο διαφορετική. 
Όταν βρεις χρόνο και μπορείς, δοκίμασε το και ενημέρωσε μας!

**Comment by drpaneas** [comment]
Παλι δεν παίζει

```
line 149: "2" : syntax error: operand expected (error token is ""2" ")
```

Φαντάζομαι ότι οφείλεται σε ένα από τα παρακάτω:
1. Δεν χρησιμοποιώ bash αλλά zshell
2. Το Mac έχει ελαφρώς διαφορετική υλοποιήση των κλασσικών εντολών (βλ. `sed`) για παράδειγμα.

Γράψε ένα τεστάκι:

```
Δεδομένου ότι ο χρήστης έχει κανει git-clone και διαθέτει το mpv
Οταν τρέχει το script και επιλέγει τον 2ο σταθμό
Τότε η εντολή που πρέπει να τρέξει είναι η "τάδε"
```

**Comment by JohnGavr** [comment]
Ευχαριστώ για την απάντηση, αρχικά να ενημερώσω ότι και εγώ χρησιμοποιώ zshell και δεν αντιμετωπίζω κάποιο πρόβλημα. Λόγω του ότι δεν έχω στην κατοχή μου κάποιο mac δεν μπορώ να βοηθήσω περισσότερο.

**Comment by drpaneas** [comment]
@JohnGavr 

Βαλε αυτό https://github.com/CerebruxCode/shelldio/pull/27/commits/7f390ac1517881e134d57b21c32b7b1678f7d27c το patch και θα παίξει.

**Comment by cerebrux** [comment]
@drpaneas μπορεις να δεις λίγο το τελευταίο commit https://github.com/CerebruxCode/shelldio/commit/785e63833493b387da05529aa89f8a66eeb443f8 (ή το pull request #43 ) 

Αν σου δουλεύει να πάει για merge
