### ISSUE TITLE
Ενσωματωμένοι σταθμοί

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#14]
Το βρίσκω αρκετά ... περίεργο να κατεβάζω 3 πράγματα:
* το shelldio
* το radio.txt
* το mpv

Θα προτιμούσα να έχει ενσωματωμένους σταθμούς, χωρίς να αναγκάζει τον χρήση να κατεβάσει ξεχωριστά το αρχείο με τους σταθμούς.

**Comment by cerebrux** [comment]
fixed in 7f2b801daad145f8b0c61d374d9dea482c33d4e2
