### ISSUE TITLE
Ελεγχος εγκυρότητας του αρχείου σταθμών

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#15]
Η structure του αρχείου που αποθηκεύει τους σταθμούς είναι plain text χωρίς καμία γνωστή μορφή. Θα ήθελα να μπορώ να κάνω parse το συγκεκριμένο αρχείο σαν YAML, έτσι ώστε να μπορώ να το διαβάσω από διάφορα άλλα προγράμματα και βιβλιοθήκες. Υπάρχουν πολλοί λόγοι που βοηθάει να έχεις ένα structured db.

**Comment by zoispag** [comment]
Βασικά, με εξαίρεση το file extension, το αρχείο είναι ένα άρτιο comma-delimited csv. Προγραμματιστικά, ένα csv διαβάζεται πολύ εύκολα. Imho δεν βρίσκω λόγο να γίνει κάποια μετατροπή σε yml.

**Comment by drpaneas** [comment]
Το προβλημα δεν είναι το διάβασμα, αλλά η εγκυρότητα του αρχείου. Με έναν απλό έλεγχο, αν ελεξεις ότι κάθε γραμμή έχει αποκλειστικά ένα και μόνο ένα κόμμα, τότε είμαστε κομπλέ. Δεν χρειάζεται yaml, ή κάτι άλλο.

**Comment by zoispag** [comment]
This is done
