### ISSUE TITLE
Δεν γίνεται έλεγχος εγκυρότητας του αρχείου

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#16]
Αν παω και γράψω ασυναρτησίες ή ακόμα αν κάνω ένα λάθος στην συμπλήρωση του αρχείου.txt το shelldio δεν το παίρνει χαμπάρι. Θα ήθελα να μπορεί να κάνει check το validity του αρχείου πριν το χρησιμοποιήσει.

**Comment by JohnGavr** [comment]
Τα link για τα web radio δεν έχουν συγκεκριμένη δομή ώστε να προστεθεί κάποιος έλεγχος. Λόγω του ότι η κάθε γραμμή στα txt files είναι 
```Όνομα σταθμού,link σταθμού```
Θα μπορούσαμε να ελέγχουμε αν μετά το κόμμα είναι url.

**Comment by drpaneas** [comment]
> Τα link για τα web radio δεν έχουν συγκεκριμένη δομή ώστε να προστεθεί κάποιος έλεγχος.

Ναι αυτο λεω. Θα πρεπει να εχουν δομή. πχ αυτο το αρχειο ειναι εγγυρο?

```
sdf,link
sds,   link
asd,,,link
```

Αν οχι, θα ηθελα να μου βγαλει σχετικο σφαλμα το script: "Το αρχείο με τους σταθμούς έχει προβλημα". Για να μην καθεσαι να γραφεις parser, χρησιμοποιήσε μία έτοιμη data structure, πχ yaml.

> Θα μπορούσαμε να ελέγχουμε αν μετά το κόμμα είναι url.

Ναι, γιατι οχι. Σε 2ο βήμα ακούγεται καλό check.

**Comment by cerebrux** [comment]
Στην νέα έκδοση δεν θα χρειάζεται ο χρήστης να επεμβαίνει με το χέρι τους για τους σταθμούς. Το σωστό είναι να μας λέει να βάλουμε τον σταθμός και έπειτα αυτός θα τρέχει:

```
shelldio --fresh
```
και θα του έρθουν νέοι σταθμοί. Μετά μπορεί να τους προσθέσει στα αγαπημένα του με το `shelldio --add`
