### ISSUE TITLE
Προσθήκη σταθμών

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#17]
Θα ήθελα να μπορώ να προσθέσω σταθμούς στο shelldio χρησιμοποιώντας το shelldio.
πχ 

```
shelldio add <name> <address>
```

**Comment by cerebrux** [comment]
Έχει αναφερθεί στο #20

**Comment by cerebrux** [comment]
fixed in https://github.com/CerebruxCode/shelldio/commit/bbebd51b5a3af6329a79bcd31da917eeca89c37e

**Comment by cerebrux** [comment]
7f2b801daad145f8b0c61d374d9dea482c33d4e2
