### ISSUE TITLE
Αφαίρεση σταθμών

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#18]
Θα ήθελα να μπορώ να αφαιρέσω σταθμούς στο shelldio χρησιμοποιώντας το shelldio.
πχ 

```
shelldio rm <name> <address>
```

**Comment by cerebrux** [comment]
Έχει αναφερθεί στο #20

**Comment by cerebrux** [comment]
fixed 7f2b801daad145f8b0c61d374d9dea482c33d4e2
