### ISSUE TITLE
Λίστα σταθμών

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#19]
Θα ήθελα να μπορώ να εμφανίσω την λίστα με τους σταθμούς στο shelldio χρησιμοποιώντας το shelldio.
πχ 

```
shelldio list <name> <address>
```

**Comment by cerebrux** [comment]
Έχει αναφερθεί στο #20

**Comment by cerebrux** [comment]
fixed in 7f2b801daad145f8b0c61d374d9dea482c33d4e2
