### ISSUE TITLE
εντολή για update

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#21]
Αν υπάρχει καινούρια έκδοση του shelldio θα ήθελα να μπορώ να την εγκαταστήσω μέσω από το ίδιο το shelldio

πχ

```
shelldio update
```

**Comment by cerebrux** [comment]
Έχει αναφερθεί στο #20

**Comment by cerebrux** [comment]
Αυτή την στιγμή υπάρχουν δυο τρόποι εγκατάστασης.

- Έχεις Arch Linux : Ωραία... η αναβάθμιση θα έρθει αυτόματα στο επόμενο update.
- Δεν έχεις Arch: Έχεις κατεβάσει το πρόγραμμα με `git clone` οπότε μπορείς να τρέξεις ένα `git pull` για να δεις αν έχει βγεί νεα έκδοση. (Έχουν γίνει Update οι οδηγίες στο  commit b008bcb)

Δεν μπορώ να σκεφτώ άλλον τρόπο, εκτός και αν φτιάξει κάποιος flatpack/snap και να τελειώσουμε με το source install via git clone :) 

Κλείνω προσωρινά. Ανοίξτε το αν έχετε καμιά άλλη ιδέα.

**Comment by drpaneas** [comment]
Εχω μία ιδέα: @cerebrux  please re-open

* Φτιάξε μία εντολή shelldio --version η οποία θα σου δείχνει την έκδοση του script διαβάζοντας στην ουσία μία μεταβλητή (πχ 2)
* Την μεταβλητή θα την αλλάζει όταν βγάζεις καινούρια έκδοση (πχ 3)
* Οταν ο χρήστης δίνει shelldio --upgrade τότε θα ελέγχει αν το shelldio --version (2) είναι μικρότερη με το αντίστοιχο από το github (κάνοντας curl και grep μπορείς να το πάρεις) ή να έχεις και ένα μεμονομένο αρχέιο που λέγεται VERSION στο repo και να συγκρίνει αυτό.
* Αν είναι η τοπική έκδοση είναι μικρότερη από την έκδοση στο github, τότε να ενημερώνει τον χρήση ότι υπάρχει καινούρια έκδοση και να του δείχνει το `changlog`. Κατόπιν να τον ρωταει αν θελει να κανει update
* Το update στην ουσια θα κανει replace το ίδιο αρχέιο το σκριπτ κατεβάζοντας την καινουρια εκδοση `https://github.com/CerebruxCode/shelldio/blob/v2.0/shelldio.sh` οπότε το version πρεπει να είναι ίδιο με το `tag`
* Θα κάνει επαλήθευση βλέποντας την καινούρια τιμή της μεταβλητής version

Αλλος τρόπος είναι να κάνει update χρησιμοποιώντας το git hash, αλλά προυποθέτει οτι το αρχείο τρέχει μέσα από το git directory, οπότε θα το απέφευγα αυτό, εκτός κι αν στο version δίνεις το sha του commit καθε φορα που κανεις push.

**Comment by cerebrux** [comment]
Καλή ιδέα αλλά εμπειρικά μπορώ να σου επιβεβαιώσω ότι δεν θα το κάνει κανένας. 

Εδώ βλέπω σε γκρουπ που έχω στείλει για την έκδοση να μου λένε ότι χρησιμοποιούν το παλιό ακόμα που λεγόταν bash_radio.sh και ότι καααααποια στιγμή θα δοκιμάσουν το νέο (το οποίο είναι κλάσης αχνότερο)

Όποτε είναι και θέμα effort per added value.
Εδώ είναι 0 όποτε τσάμπα ο κόπος.

Το σωστο είναι να γίνει μέσω Travis ένα auto snap build να τελειώνουμε ώστε μετά από κάθε push στο stable να στέλνει νέα έκδοση.
