### ISSUE TITLE
To Github δεν εχει concept για Epics

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/shelldio#23]
To Github δεν εχει concept για Epics. Αυτό το issue ειναι ένα epic issue.
Ανοιξε ξανά τα επιμέρους issues που έκλεισες και βάλε τα τα τα id τους εδώ, έτσι ώστε όταν γίνουν fixed, τότε θα κλείσει και αυτό το epic.

Δες: https://github.com/marketplace/actions/epic-issues-for-github

_Originally posted by @drpaneas in https://github.com/CerebruxCode/shelldio/issues/20#issuecomment-691169604_

**Comment by cerebrux** [comment]
@drpaneas διευκρίνισε μου : 

- Χρειάζεται σε κάθε issue που θα είναι μέρος ενός epic issue, να βάλω και σε αυτά tag "epic" ή αρκεί μονο το reference στο bug number

- μπορείς να τσεκάρεις αν είναι σωστό ? https://github.com/CerebruxCode/shelldio/blob/develop/.github/workflows/epic.yml γιατί δεν το βλέπω στο κουμπί actions (tab). Χρειάζεται να κάνω κάτι άλλο ?

**Comment by drpaneas** [comment]
Δεν ξερω, δεν το εχω χρησιμοποιήσει. Συνήθως είναι καθήκον αυτού που κλείνει/δουλεύει στο issue να ενημερώσει το epic. Οπως και να χει, το github θα ενημερώσει το history κάνοντας strikethrough, οποτε δεν θα "ξεχαστεί" κατι. Φαντάζομαι για να ενημερωθεί το Actions, πρεπει να γινει trigger. Για να γίνει τριγγερ πρεπει να κλεισεις καποιο απο τα issues.

ΥΣ: Νομίζω δε χρειαζεται να εχουν ολα το epic label, αλλα δεν ειμαι και σιγουρος. test it ;)

**Comment by cerebrux** [comment]
Δεν δουλεύει σωστά. F Dis $it
