### ISSUE TITLE
Λίστα To Do

### ISSUE THREAD

**Issue by JohnGavr** [CerebruxCode/shelldio#3]
Λίστα κώδικα:

- [x] Μετονομασία gr_stations.txt σε my_stations.txt

- [x] Μετονομασία greek_stations σε all_stations.txt

- [x] Ενημέρωση README αρχείου για την βοήθεια των AUR επισκεπτών

- [x] Διόρθωση paths (Default path .shelldio/)

- [x] Shellcheck τον κώδικα μετά το fork (clean start)

- [x] Επικαιροποίηση της λίστας των διαθέσιμων σταθμών

**Comment by cerebrux** [comment]
Πρόσθεσα οτι πέρασε ο κώδικας απο Shellcheck και είναι πλέον καθαρός

**Comment by JohnGavr** [comment]
Πλέον το script είναι λειτουργικό με τις αλλαγές. Διαβάζει το my_stations.txt σαν default αρχείο σταθμού

**Comment by cerebrux** [comment]
fixed with commits from

- cebda6130e7233e7f933d19fc5f6d0fdbaae905c till 1eaed8bb6c73294e06a0aee3c8b32a714f971c36
