### ISSUE TITLE
Δε γίνεται έλεγχος του υποφάκελου

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#36]
Οταν κατεβαζεις το αρχειο το αποθηκευεις σε εναν υποφακελο.
Αν δεν υπαρχει, θα αποτυχει.

https://github.com/CerebruxCode/shelldio/blob/stable/shelldio.sh#L179

EDIT: Τωρα ειδα οτι το βαζεις: https://github.com/CerebruxCode/shelldio/blob/stable/shelldio.sh#L219
Κανε ελεγχο αν δημιουργθηκε ο φακελος καθως μπορει να αποτύχει (πχ permissions) ή να υπάρχει ήδη (οπότε να κάνεις silence το μύνημα σε αυτη τη περιπτωση)

**Comment by JohnGavr** [comment]
@drpaneas 
Παραθέτω τον συγκεκριμένο κώδικα ελέγχου.
Στην πρώτη συνθήκη if ελέγχει αν υπάρχει ο φάκελος .shelldio στον home folder. Δημιουργείτε ο φάκελος .shelldio μόνο στην περίπτωση που δεν υπάρχει. Δεν νομίζω να υπάρχει πρόβλημα με τα permissions. 
https://github.com/CerebruxCode/shelldio/blob/0f65b2dab6e8c7a25b8ae3a422f1308420ae11a4/shelldio.sh#L206-L229

**Comment by zoispag** [comment]
> Δεν νομίζω να υπάρχει πρόβλημα με τα permissions.

Συμφωνώ, το home folder θα πρέπει να είναι πάντα writable από τον εκάστοτε user και ο φάκελος θα έχει δημιουργηθεί από τον ίδιο χρήστη στην προηγούμενη εκτέλεση, οπότε θα ανήκει στο σωστό user:group.

**Comment by drpaneas** [comment]
> @drpaneas
> Παραθέτω τον συγκεκριμένο κώδικα ελέγχου.
> Στην πρώτη συνθήκη if ελέγχει αν υπάρχει ο φάκελος .shelldio στον home folder.

Στην περίπτωση που αναφέρεις παίζει σωστά (χωρίς ορίσματα). Αν η πρώτη χρήση είναι με όρισμα τότε υπάρχει πρόβλημα. Δες το παρακάτω reproducer:


### Reproducer

1. Κατέβασε το shelldio.sh

```shell
wget https://raw.githubusercontent.com/CerebruxCode/shelldio/stable/shelldio.sh
```

2. Σιγουρέψου ότι **δεν** υπάρχει το ` ls -l ~/.shelldio/`
```
$ ls -l ~/.shelldio
ls: /Users/drpaneas/.shelldio: No such file or directory
```

3. Τρέξε το script με το την `-f` flag:

```shell
$ bash -x ./shelldio.sh -f
...
...
...
+ echo 'Γίνεται λήψη του αρχείου των σταθμών από το αποθετήριο.'
Γίνεται λήψη του αρχείου των σταθμών από το αποθετήριο.
+ sleep 1
+ curl -sL https://raw.githubusercontent.com/CerebruxCode/shelldio/stable/.shelldio/all_stations.txt --output /Users/drpaneas/.shelldio/all_stations.txt
+ exit 0
```
4. Επαλήθευσε αν υπάρχει το αρχείο

```shell
$ ls -l /Users/drpaneas/.shelldio/all_stations.txt
ls: /Users/drpaneas/.shelldio/all_stations.txt: No such file or directory
```

Οπως βλέπεις:
1. Δεν έχει κατεβάσει το αρχείο (γιατί δεν υπάρχει ο φάκελος)
2. Εχει κάνει exit με `0` exit code, αντί για 1.

Οπότε 2 bugs. Πάμε και στο άλλο:

> > Δεν νομίζω να υπάρχει πρόβλημα με τα permissions.
> 
> [...] θα πρέπει να είναι πάντα [...]

last famous words :P Συμφωνώ με αυτό που λέτε, αλλά δεν μπορείς να ξέρεις τι ανωμαλίες έχει κάνει ο άλλος στο σύστημά του. πχ μπορεί να έχει προσωρινά _χαλάσει_ την ~$HOME` μεταβλητή ή να τρέχει το script σε κάποιο container όπου ο χρήστης δεν έχει `$HOME`, μπορεί το script να το έχει κατεβάσει σε άλλον δίσκο και να έχει το home partition σε άλλο δίσκο με άλλο filesystem (και για καποιο λόγο να βγαζει προβλημα), μπορουν ένα κάρο πράγματα... οπότε βάλε ένα `if`, δεν κοστίζει κάτι.

### Reproducer

```shell
adduser --system --no-create-home --group testuser
su - testuser
τρέξε το script και θα δεις να αποτυγχαίνει
```

**Comment by JohnGavr** [comment]
Προστέθηκε ο έλεγχος υποφακέλου στην επιλογή --f. 
Τώρα αν ο χρήστης έκανε κάποιες ανωμαλίες και για παράδειγμα δεν έχει $HOME πρέπει να αλλάξει όλο το script.

**Comment by zoispag** [comment]
Χμμ..
```bash
if [ ! -f "$HOME/.shelldio" ]; then
```
Αν το `$HOME` δεν εχει γίνει export για τον οποιοδήποτε λόγο, τότε το folder θα είναι `/.shelldio` και θα προσπαθήσει να το δημιουργήσει στο root path. Μήπως να κάνουμε expand το condition, να τρέχει με την προυπόθεση ότι `-z "$HOME"`?

**Comment by drpaneas** [comment]
> Προστέθηκε ο έλεγχος υποφακέλου στην επιλογή --f.
`
Ωραία, πιστεύω είναι αρκετό για να κλείσουμε το issue ;) :D

> Τώρα αν ο χρήστης έκανε κάποιες ανωμαλίες και για παράδειγμα δεν έχει $HOME πρέπει να αλλάξει όλο το script.

Σε άλλο PR, μπορείς να προσθέσεις έλεγχο ENV variables στην αρχή του script, κι αν δεν υπάρχουν να τις κάνεις export εσύ ;)

**Comment by cerebrux** [comment]
> Χμμ..
> 
> ```shell
> if [ ! -f "$HOME/.shelldio" ]; then
> ```
> 
> Αν το `$HOME` δεν εχει γίνει export για τον οποιοδήποτε λόγο, τότε το folder θα είναι `/.shelldio` και θα προσπαθήσει να το δημιουργήσει στο root path. Μήπως να κάνουμε expand το condition, να τρέχει με την προϋπόθεση ότι `-z "$HOME"`?

Υπάρχει περίπτωση όταν τρέχεις π.χ. μια εφαρμογή στο shell να μην γνωρίζει το shell την τιμή της $HOME ? Αυτό νομίζω θα ήταν χοντρό bug όχι μόνο στο shelldio αλλά και στο όλο λειτουργικό σύστημα του LINUX/Unix XAXAXAX :)

**Comment by zoispag** [comment]
> > Χμμ..
> > 
> >   
> >     
> >       
> >     
> >   if [ ! -f "$HOME/.shelldio" ]; then
> > Αν το `$HOME` δεν εχει γίνει export για τον οποιοδήποτε λόγο, τότε το folder θα είναι `/.shelldio` και θα προσπαθήσει να το δημιουργήσει στο root path. Μήπως να κάνουμε expand το condition, να τρέχει με την προϋπόθεση ότι `-z "$HOME"`?
> 
> Υπάρχει περίπτωση όταν τρέχεις π.χ. μια εφαρμογή στο shell να μην γνωρίζει το shell την τιμή της $HOME ? Αυτό νομίζω θα ήταν χοντρό bug όχι μόνο στο shelldio αλλά και στο όλο λειτουργικό σύστημα του LINUX/Unix XAXAXAX :)

Μόνο αν για κάποιο λόγο έχεις κάνεις unset στο ίδιο session τρέχοντας άλλο script! 👿

**Comment by cerebrux** [comment]
> > > Χμμ..
> > > if [ ! -f "$HOME/.shelldio" ]; then
> > > Αν το `$HOME` δεν εχει γίνει export για τον οποιοδήποτε λόγο, τότε το folder θα είναι `/.shelldio` και θα προσπαθήσει να το δημιουργήσει στο root path. Μήπως να κάνουμε expand το condition, να τρέχει με την προϋπόθεση ότι `-z "$HOME"`?
> > 
> > 
> > Υπάρχει περίπτωση όταν τρέχεις π.χ. μια εφαρμογή στο shell να μην γνωρίζει το shell την τιμή της $HOME ? Αυτό νομίζω θα ήταν χοντρό bug όχι μόνο στο shelldio αλλά και στο όλο λειτουργικό σύστημα του LINUX/Unix XAXAXAX :)
> 
> Aν για κάποιο λόγο έχεις κάνεις unset στο ίδιο session τρέχοντας άλλο script!?

Ωχ ! Αυτό θα είναι evil as hell :) 

Πέρα απο την πλάκα πως θεωρείς θα είναι πιο ασφαλές για έλεγχο ? Έχεις κάνα snippet ?
