### ISSUE TITLE
sort σταθμών

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#39]
Οταν ο χρήστης προσθέτει έναν σταθμό, αυτός μπορεί να μην είναι sorted. Προσωπικά θα ήθελα το αρχέιο να είναι sorted με βάση των αριθμό των ραδιοκυμάτων.  Οπότε αφού προσθέσει ο χρήστης τον σταθμό, θα ήθελα το script να κανει και ενα sort το αρχείο.

https://github.com/CerebruxCode/shelldio/blob/stable/shelldio.sh#L96 (απλά το κάνει append)

**Comment by cerebrux** [comment]
Εννοείς sorting με βάση τα FM ?

Αν ναι τότε θα πρέπει να σου υπενθυμίσω ότι μιλάμε για ιντερνετικα ραδιόφωνα και ότι ο κόσμος τα ψάχνει με βάση το Όνομα :) 

Please elaborate :)

**Comment by drpaneas** [comment]
> Εννοείς sorting με βάση τα FM ?
> 
> Αν ναι τότε θα πρέπει να σου υπενθυμίσω ότι μιλάμε για ιντερνετικα ραδιόφωνα και ότι ο κόσμος τα ψάχνει με βάση το Όνομα :)
> 
> Please elaborate :)

Με βάση το όνομα τότε

**Comment by cerebrux** [comment]
Good point. Να τα κάνει αλφαβητικά για να τα εντοπίζει εύκολα.
Οκ @JohnGavr ας το κάνουμε στο all_stations σε πρώτη φάση γιατί το my_stations ανήκει στον χρήστη και μπορεί να τα θέλει όπως τα θέλει η όπως τα κάνει add
