### ISSUE TITLE
περιορισμένη προσθήκη σταθμών

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#41]
Οταν επιλέγω να προσθέσω σταθμό, με αναγκάζει να επιλέξω από μία λίστα. Εγω θέλω να προσθέσω δικό μου σταθμό, να δίνω ένα όνομα και ένα νούμερο (FM).

PS: Αν δεν υποστηρίζεται αυτό το feature, τότε οκ.

**Comment by cerebrux** [comment]
Ανοίγεις το αρχείο και το προσθέτεις εκεί που θες στο my_stations.

Αλλά έτσι χάνει οι κοινότητα σταθμούς που μπορούμε να μοιραζόμαστε :)

Αν δεις στο τέλος του Readme γράφουμε ότι καλό είναι να μας το στέλνουν τον σταθμό να τον προσθέτουμε και να κάνουν απλά 

shelldio --fresh 

'tsabaout community :)
