### ISSUE TITLE
Να μην χρειάζεται να το κατεβάσω

### ISSUE THREAD

**Issue by drpaneas** [CerebruxCode/shelldio#42]
* Φτιαξε ενα short link για το `https://raw.githubusercontent.com/CerebruxCode/shelldio/stable/shelldio.sh` πχ get.shelldio.gr
* Ο χρήστης θα πρέπει να δώσει μόνο: `curl -sLS get.shelldio.gr | sh`

**Comment by cerebrux** [comment]
Κανενας δεν το κατεβαζει έτσι. Μόνο οι έμπειροι χρήστες :) 

Οι περισσότεροι ακολουθούν τις οδηγίες μας.

Αν το κάνει όπως λες τότε  χάνει την δυνατότητα για να κάνει εγκατάσταση και updates όπως γράφει το Readme.
Επίσης έτσι δεν θα ξέρουμε που το βάζει. 

Ακολουθώντας τις οδηγίες κατά γράμμα υπάρχει ένας έλεγχος στην εμπειρία εγκατάστασης από μέρους μας για να ξέρουμε τι μπορεί να πήγε στραβά.
