### ISSUE TITLE
Το όνομα του αρχείου καλύτερα ως μεταβλητή

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/shelldio#55]
Στην περίπτωση που αλλάξει για κάποιο λόγο το όνομα του αρχείου στο μέλλον, ίσως ξεχάσουν να το αλλάξουν και σε αυτό το σημείο. Χρησιμοποιώντας την μεταβλητή έχεις το κεφάλι σου ήσυχο ;)

```suggestion
	--reset: Καθαρίζει τη λίστα αγαπημένων, διαγράφοντας το αρχείο $my_stations
```

_Originally posted by @drpaneas in https://github.com/CerebruxCode/shelldio/pull/53#discussion_r491747624_

**Comment by zoispag** [comment]
This is done
