### ISSUE TITLE
Το αρχείο που θα έρχεται από το repo πρέπει να είναι valid.

### ISSUE THREAD

**Issue by cerebrux** [CerebruxCode/shelldio#62]
Αρχικά το μετέφερα πιο κάτω.

Αλλά στη συνέχεια υλοποίησα αυτό:
> Πριν ελέγξεις την εγκυρότητα, έλεγξε την ύπαρξη.

Οπότε το επέστρεψα στην αρχή, μετά τα binaries check. Το αρχείο που θα έρχεται από το repo πρέπει να είναι valid. (προτείνω ένα github action να τσεκάρει το csv για validity)

_Originally posted by @zoispag in https://github.com/CerebruxCode/shelldio/pull/53#discussion_r491846134_

**Comment by zoispag** [comment]
This is done
