### ISSUE TITLE
Develop and Stable branches do not match

### ISSUE THREAD

**Issue by zoispag** [CerebruxCode/shelldio#79]
Υπάρχει απόκλιση μεταξύ Develop και Stable branches. To stable λέει 2.3 και το develop 2.2

Αυτό κάνει πολύ δύσκολη τη δημιουργία νέων PR. Νομίζω ότι πρέπει να γίνει μία αναδιοργάνωση στον τρόπο που τρέχουν τα branches.

**Comment by cerebrux** [comment]
Σκέφτομαι μήπως να καταργήσω εντελώς το dev branch για να μην κάθεται ανάμεσα στα PR.

Open to workflow suggestions. 

Να θυμηθώ : Με βάση του που θα καταλήξω να κάνω update το CONTRIBUTING.md file με τις κατάλληλες οδηγίες.

**Comment by zoispag** [comment]
Συμφωνώ με την κατάργηση του dev branch.
Υπάρχει άραγε κάποιος τρόπος να γίνει χρήση πραγματικών releases? 
Πχ, κάνεις όσα merge θελεις στο main branch, και tagάρεις την version 2.5, ως πραγματικό release.
Το μόνο ερώτημα εδώ, είναι πως να "εξηγήσεις" ότι το clone θα πρεπει να γίνει χρησιμοποιώντας ένα tag αντί για branch. 
Let me think about it.

**Comment by cerebrux** [comment]
Η αρχική σκέψη ήταν:

1. Εμείς παίζουμε και δοκιμάζουμε νέα χαρακτηριστικά στο develop και δεν μας νοιάζει αν εμφανιστεί κατά λάθος κάποιο bug στο develop. Μπορεί να δουλεύουμε μέρες σε αυτό ή και μήνες.
2. Το stable (master) είναι αυτό που κάνει clone ο avarage joe για να χρησιμοποιήσει την εφαρμογή. 
3. Όταν νιώσουμε ότι το Develop είναι stable enough (τρόπος του λέγειν) το κάνω merge --> stable οπότε ο avarage joe κάνει ένα git pull και του έρχεται η νέα έκδοση (εξαιρείται ο Arch user που έχει package από AUR)
4. Αφού γίνει το release, το develop (έπρεπε) είναι synced με το stable (Αφού από εκεί έγινε το merge) οπότε ξεκινάει ένα νέο loop και πάμε πάλι στο --> 1.

Το release αυτή την στιγμή το μόνο που εξυπηρετεί είναι να ενημερώνει και επειδή είναι tagging το διαβάζει το PKGBUILD αρχείο του AUR που ανεβάζω για τους χρήστες Arch ώστε να τους πάει upgrade στην νέα έκδοση.

Άρα δεν με πειράζει να πάρει πόδι το develop branch αρκεί 2 πράγματα δεν πρέπει να "σπάσουν"

1. το stable που κάνει clone η κυρα Βαγγελιώ
2. Το Release/tag που το θέλω για το AUR

**Comment by zoispag** [comment]
Kudos για την κυρα Βαγγελιώ! 😛

**Comment by cerebrux** [comment]
@zoispag @JohnGavr @drpaneas
Σύμφωνα με αυτά που είπαμε πάνω, λέω να μεταβώ από το παραδοσιακό μοντέλο branching (main[production ready] - develop[testing]) σε αυτό που προτείνει ως μοντέλο "continuous delivery" το github https://guides.github.com/introduction/flow/
Θα ήθελα την άποψή σας.

**Comment by drpaneas** [comment]
Ρε συ ενα script είνα ..., και που έχουμε φτιαξει ολόκληρο repo είναι too much imho. Δεν βρισκω ιδιαιτερο νοημα να έχεις stable/testing branch απο την στιγμη που δεν εχεις tests.
