### ISSUE TITLE
Φαίνεται ο αριθμός της λίστας του σταθμού όταν παίζει

### ISSUE THREAD

**Issue by billniakas** [CerebruxCode/shelldio#82]
![Screenshot from 2020-10-03 12-09-35](https://user-images.githubusercontent.com/12209936/94987755-59be0200-0571-11eb-9fb2-c5fe2f5fb730.png)

Κρύψτε το με ένα απλό `cut -d "]" -f2`

ΥΓ. κρυψτε και τον κερσορα

**Comment by cerebrux** [comment]
Δες λίγο αυτό https://github.com/CerebruxCode/shelldio/issues/76 αν είναι αυτό που λέει εκεί τότε μπορείς να το κλήσεις αυτό.

Είναι σκόπιμο να εμφανίζεται ο αριθμός.

Για τον κέρσορα θα ανοιχτεί ξεχωριστό issue.

**Comment by billniakas** [comment]
Αν κάποιος ακούει τακτικά αυτόν το σταθμό ξέρει και το νούμερο. Το θέμα είναι αισθητικό.

**Comment by cerebrux** [comment]
Έχουμε δυο ειδών χρήστες :

1. Αυτοί που ακούνε 1-2 σταθμούς μόνο
2. Αυτοί που δεν χρησιμοποιούν το my_stations αλλά επιλέγουν με το κλασσικο "ζάπινγκ" καναλιών και δεν έχουν κάτι σταθερό

Αυτοί που είναι στο (1) έχεις δίκιο άκουν στανταριακια και μάλιστα σε επόμενη έκδοση (ήδη είναι στο develop) θα μπορούν να κάνουν γρήγορη εκκίνηση απευθειας του σταθμού.

Αυτοι που είναι στο δυο, μπορεί να θέλουν να βλέπουν τον αριθμό που επέλεξαν ώστε να όταν κλείσουν να θυμούνται ποιο είχαν ακούσει (είναι πιο εύκολος ο αριθμός από τα περίεργα ενός τα σταθμών).

Άρα πρέπει να βρεθεί μια μέση λύση που να καλύπτει και τις δυο πλευρές.

Ίσως ο αριθμός να φύγει από εκεί και να πάει κάπου δεξιά επάνω η αριστερά. Θέλει δοκιμές :)

Άρα ας το αφήσουμε ανοιχτό το issue
