### ISSUE TITLE
Προσθήκη Bar Legend Radio

### ISSUE THREAD

**Issue by arvchristos** [CerebruxCode/shelldio#87]
Θα μπορούσατε να προσθέσετε τον Bar Legend Radio στους σταθμούς?

https://www.barlegendradio.net/

`Bar Legend Radio,https://solid24.streamupsolutions.com:2199/tunein/nilxzqeg.pls`

**Comment by cerebrux** [comment]
Ωραίος σταθμός ! Θα τον προσθέσουμε σύντομα και θα ενημερωθείς !

**Comment by cerebrux** [comment]
Ο σταθμός μπήκε και οι χρήστες του shelldio μπορούν να τρέξουν:
```
shelldio --fresh
```
για να το λάβουν

**Comment by arvchristos** [comment]
@cerebrux Ευχαριστώ πολύ!!
