### ISSUE TITLE
Εκτέλεση χωρίς εγκατάσταση μέσω curl

### ISSUE THREAD

**Issue by catman85** [CerebruxCode/shelldio#99]
```sh
curl link | bash
```

**Comment by cerebrux** [comment]
Μπορείς λίγο να περιγράψεις το σκεπτικό σου ? τι ακριβώς προτείνεις ? Tip ? Feature ? Προσθήκη κάποιας λειτουργίας ? Προσθήκη στο documentation ?

**Comment by catman85** [comment]
Είναι ένα feature. 
Θεωρητικά θα μπορούσε να τρέξει και έτσι η εφαρμογή:
```sh 
curl https://raw.githubusercontent.com/CerebruxCode/shelldio/stable/shelldio.sh | bash
```
Με κάποιες τροποποιήσεις στην παραπομπή του αρχείου _all_stations.txt_
```https://raw.githubusercontent.com/CerebruxCode/shelldio/stable/.shelldio/all_stations.txt```

**Comment by cerebrux** [comment]
Δυστυχώς αυτός ο τρόπος δεν επιτρέπει την χρήση αρκετών από τις λειτουργίες που έχουν ενσωματωθεί και για να δουλέψει χρειάζονται αλλαγές σε κάποια σημεία του κώδικα, τα οποία στο μέλλον όμως μπορεί να χρειαστούν πάλι προσαρμογές.
Οπότε αυτό δεν θα μπορέσουμε να το υποστηρίξουμε αυτή την στιγμή οπότε και θα κλείσουμε το issue εδώ.
Αν παρόλα αυτά έχεις να στείλεις κάποιο PR που να προσθέτει αυτή την λειτουργία χωρίς να "σπάει" τις υπάρχουσες δυνατότητες τότε θα χαρούμε να το τεστάρουμε.
